package ru.dekabrsky.italks.scopes

object Scopes {
    const val SCOPE_APP = "SCOPE_APP_ROOT"
    const val SCOPE_APP_ROOT = "SCOPE_APP_ROOT"
    const val SCOPE_FLOW_TABS = "SCOPE_FLOW_TABS"

    const val SCOPE_FLOW_CHATS = "SCOPE_FLOW_CHATS"
    const val SCOPE_FLOW_MATERIALS = "SCOPE_FLOW_MATERIALS"
    const val SCOPE_FLOW_SCENARIOS = "SCOPE_FLOW_SCENARIOS"
    const val SCOPE_FLOW_DIALINGS = "SCOPE_FLOW_DIALINGS"
    const val SCOPE_FLOW_STATS = "SCOPE_FLOW_STATS"
    const val SCOPE_FLOW_NOTIFICATIONS = "SCOPE_FLOW_NOTIFICATIONS"
    const val SCOPE_FLOW_LOGIN = "SCOPE_FLOW_LOGIN"
    const val SCOPE_FLOW_GAME = "SCOPE_FLOW_GAME"
    const val SCOPE_FLOW_PROFILE = "SCOPE_FLOW_PROFILE"

    const val SCOPE_TESTER_SETTINGS = "SCOPE_TESTER_SETTINGS"
}